### PR TITLE
added vuex store

### PR DESCRIPTION
**Pull request by cecoppinger**
I think I did it right?  Let me know if there are any questions.

### CODE REVIEW

**Comment by ryanis-online** [comment]
This looks great! For the purposes of this PR, you've got my blessing, but in the future, we may want to explore the concept of [modules](https://vuex.vuejs.org/guide/modules.html#modules)

Edit: reformatted link (I'm really bad at this lol)

**Review by ryanis-online — APPROVED** [review]

**Review by iktani — APPROVED** [review]
looks good to me

**Review by simpson1986 — APPROVED** [review]
looks good

**Review by truons — APPROVED** [review]
It look great. Got my approve

**Review by zstephenj — APPROVED** [review]

**Pull request merged**
