### PR TITLE
Show appropriate dashboard

### PR DESCRIPTION
**Pull request by iktani**
Made the following changes (all frontend stuff):

- Installed Vue Router, modified main.js file to use vue router

- Added routes.js file, created two routes, '/' for home page, '/dashboard' to show either user dashboard or famer dashboard. At /dashboard, the new Dashboard.vue component decides which dashboard to show based on account type of the logged in user. 

- Added UserDashboard.vue to hold user dashboard component. Not fully built yet, currently just displays a message indicating that it is the user dashboard.

- Added temporary data to the vuex store. To test functionality, change the "AccountType" to either "farmer" or "user".

### CODE REVIEW

**Review by ryanis-online — APPROVED** [review]
Nicely done!

**Review by cecoppinger — APPROVED** [review]
Looks good to me!

**Comment by simpson1986** [comment]
Looks good

**Review by simpson1986 — APPROVED** [review]
looks good

**Review by zstephenj — APPROVED** [review]

**Pull request merged**
